config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'copyright' => 'static_pages#copyright'
  get 'sign_up' => 'static_pages#sign_up'
  get 'sign_in' => 'static_pages#sign_in'

  devise_for :artists, controllers: { sessions: "artists/sessions", passwords: "artists/passwords", registrations: "artists/registrations", confirmations: "artists/confirmations",  unlocks: "artists/unlocks"}

  resources :artists, controller: 'artists/artists', only: [:show, :index] do
    member do
      resource :profile, controller: 'artists/profiles', only: [:edit, :update], as: :artist_profile
    end
    member do
      resources :albums, controller: 'artists/albums', only: [:index, :new, :create], as: :artist_albums
    end
    collection do
      resources :albums, controller: 'artists/albums', only: [:show, :edit, :update, :destroy], as: :artist_albums do
        member do
          resources :tracks, controller: 'artists/tracks', only: [:new, :create], as: :artist_tracks
        end
        collection do
          resources :tracks, controller: 'artists/tracks', only: [:show, :edit, :update, :destroy], as: :artist_tracks
        end
      end
    end
    member do
      resources :videos, controller: 'artists/videos', only: [:index, :new, :create], as: :artist_videos
    end
    collection do
      resources :videos, controller: 'artists/videos', only: [:edit, :update, :destroy], as: :artist_videos
    end
    member do
      resources :shows, controller: 'artists/shows', only: [:index, :new, :create], as: :artist_shows
    end
    collection do
      resources :shows, controller: 'artists/shows', only: [:edit, :update, :destroy], as: :artist_shows
    end
    member do
      resources :merch, controller: 'artists/merches', only: [:index, :new, :create], as: :artist_merches
    end
    collection do
      resources :merch, controller: 'artists/merches', only: [:show, :edit, :update, :destroy], as: :artist_merches do
        member do
          resources :purchases, controller: 'artists/merch_purchases', only: :create, as: :artist_merch_purchases
        end
        collection do
          resources :purchases, controller: 'artists/merch_purchases', only: [:edit, :update, :destroy], as: :artist_merch_purchases
        end
      end
    end
    member do
      resources :microposts, controller: 'artists/microposts', only: :create, as: :artist_microposts
    end
    collection do
      resources :microposts, controller: 'artists/microposts', only: :destroy, as: :artist_microposts do
        member do
          resources :comments, controller: 'artists/comments', only: :create, as: :artist_micropost_comments
        end
        collection do
          resources :comments, controller: 'artists/comments', only: :destroy, as: :artist_micropost_comments
        end
      end
    end
    member do
      resources :relationships, only: :create
    end
    collection do
      resources :relationships, only: :destroy
    end
  end

  get 'artists/:id/select_albums' => 'artists/albums#select', as: :select_artist_album
  get 'artists/:id/select_videos' => 'artists/videos#select', as: :select_artist_video
  get 'artists/:id/select_shows' => 'artists/shows#select', as: :select_artist_show
  get 'artists/:id/select_merch' => 'artists/merches#select', as: :select_artist_merch
  get 'artists/:id/merch_transactions' => 'artists/merch_purchases#index', as: :artist_merch_transactions
  get 'artists/merch/purchases/:id/edit_shipped' => 'artists/merch_purchases#edit_shipped', as: :artist_merch_transactions_edit_shipped
  get 'artists/:id/followers' => 'artists/artists#followers', as: :artist_followers

  devise_scope :artist do
    get "sign_out", to: "artists/sessions#destroy"
  end

  devise_for :fans, controllers: { sessions: "fans/sessions", passwords: "fans/passwords", registrations: "fans/registrations", confirmations: "fans/confirmations",  unlocks: "fans/unlocks"}

  resources :fans, controller: 'fans/fans', only: :show do
    member do
      resource :profile, controller: 'fans/profiles', only: [:edit, :update], as: :fan_profile
    end
  end

  get 'fans/:id/purchase_history' => 'fans/merch_purchases#index', as: :fan_purchase_history
  get 'fans/:id/following' => 'fans/fans#following', as: :fan_following

  devise_scope :fan do
    get "sign_out", to: "fans/sessions#destroy"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @artists = Artist.all
  end

  def privacy
  end

  def terms_of_use
  end

  def contact
  end

  def about
  end

  def faq
  end

  def copyright
  end

  def sign_up
    if artist_signed_in? || fan_signed_in?
      redirect_to root_url
    end
  end

  def sign_in
    if artist_signed_in? || fan_signed_in?
      redirect_to root_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">

  </div>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">

  </div>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/copyright.html.erb
<%= provide(:title, "Copyright") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">

  </div>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/faq.html.erb
<%= provide(:title, "FAQ") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">
    <div class="static-pages-title">
      <h3>faq</h3>
    </div>

    <div class="faq-mini-headlines">
      account information
    </div>

    <div class="faq-minier-headlines">
      How do I delete my account?
    </div>
    <p>First of all, I'm very sad to see that you want to delete your account. Deeply saddened... alright, I'm over it.</p>
    <p>To delete your account, both fan and artist, you need to go to your <%= link_to "settings", edit_fan_registration_path if fan_signed_in? %><%= link_to "settings", edit_artist_registration_path if artist_signed_in? %><%= "settings" if !artist_signed_in? && !fan_signed_in? %> and locate the delete button on the bottom of the page. Click it and you'll be prompted to delete your account. Beware, this is permanent and wipes you clean out of the database. No one, not even me, can get your account back </p>
    <p>If you're an artist, be sure to complete any merch orders on your account as those will remain in the database. Failure to do so may result in my laywers slamming Thor's hammer down on your front door's step. Things'll get ugly quick.</p>
    <p>Good riddance, and don't let the door slam you on the ass on your way out.</p>

    <div class="faq-mini-headlines">
      purchases and shipping
    </div>

    <div class="faq-minier-headlines">
      Why do I have to be signed into a fan account to purchase merch from an artist?
    </div>
    <p>Good question, my dear.</p>
    <p>The main reason is security. I discovered a huge security flaw that would allow just about anyone with the right amount of data to see your super-top-secret information, including your address. I recently stumbled upon this website, <a href="https://shipyourenemiesglitter.com">ship your enemies glitter</a>, and would honestly hate myself if anyone mailed you glitter because of a security flaw in this site.</p>
    <p>A far more important reason is because with a fan account you can track all the purchases you've made. This allows you to see just how much money you've blown on your favorite artists merch (if you don't give your wife your password, she'll never know). But more importantly, it allows you to see if your items have been shipped or not.</p>

    <div class="faq-minier-headlines">
      Why can't I get anything shipped outside of the U.S.?
    </div>
    <p>Because I'm too stupid.</p>
    <p>This is literally the reason. When I started this site, I figured everyone's addresses and eCommerce laws were the same. I'm not always sure how things work outside of the U.S. Typical American ignorance.</p>
    <p>I'm learning and working on how to ship to your cool countries. But for now, I can only offer shipping to the U.S.</p>
    <p>I'm sorry for being a dumbass.</p>

    <div class="faq-minier-headlines">
      How do I mark stuff as shipped?
    </div>
    <p>Simple.</p>
    <p>As an artist, go to your <%= link_to "merch transactions", artist_merch_transactions_path(current_artist) if artist_signed_in? %><%= "merch transactions" if !artist_signed_in? %> page and locate the "shipped?" column. You can click on items in this column.</p>
    <p>Upon clicking on one of these items you will be magically transported to a page where you can mark a purchase as shipped (true) or not shipped (false).</p>

  </div>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<%= render 'partials/home_header' %>
<div class="container">
  <div class="jumbotron">
    noisaea //
  </div>

  <div class="home-mini-title">
    recent artists //
  </div>
  <div class="artist-discover-genre-container-all-genres">
    <% @artists.order( 'id DESC' ).take(10).each do |artist| %>
      <div class="artist-discover-artist-container">
        <div class="artist-discover-artist-profile-image">
          <% if artist.artist_profile.profile_image == "" %>
          <div class="artist-discover-artist-no-artist-profile-image">
            <% if artist_signed_in? && artist.id == current_artist.id %>
            <p class="fan-no-profile-image-yet">you do not have a profile photo yet</p>
            <p><%= link_to "upload a profile image", edit_artist_profile_path(current_artist), class: "upload-fan-profile-image" %></p>
            <% else %>
            <p class="fan-no-profile-image-yet"><%= "#{artist.artist_name} hasn't uploaded a profile image yet" %></p>
            <% end %>
            </div>
          <% else %>
          <%= link_to artist_path(artist) do %>
            <img class="image-show" src="<%= artist.artist_profile.profile_image %>" width="210" height="210" />
          <% end %>
          <% end %>
        </div>
        <div class="artist-discover-artist-artist-name">
          <%= link_to artist.artist_name, artist_path(artist) %>
        </div>
        <div class="fan-artist-following-page-genre">
           <%= artist.artist_profile.genre.downcase %>
        </div>
        <div class="artist-follower-page-fan-following">
            has <span class="artist-follower-page-fan-following-count"><%= link_to artist.fans.count, artist_followers_path(artist) %></span>
            <% if artist.fans.count == 1 %>
            fan
            <% else %>
            fans
            <% end %>
          </div>
      </div>
    <% end %>
  </div>

  <div class="home-mini-title">
    popular artists //
  </div>
  <div class="artist-discover-genre-container-all-genres">
    <% @artists.sort_by{ |artist| -artist.fans.count }.take(10).each do |artist| %>
      <div class="artist-discover-artist-container">
        <div class="artist-discover-artist-profile-image">
          <% if artist.artist_profile.profile_image == "" %>
          <div class="artist-discover-artist-no-artist-profile-image">
            <% if artist_signed_in? && artist.id == current_artist.id %>
            <p class="fan-no-profile-image-yet">you do not have a profile photo yet</p>
            <p><%= link_to "upload a profile image", edit_artist_profile_path(current_artist), class: "upload-fan-profile-image" %></p>
            <% else %>
            <p class="fan-no-profile-image-yet"><%= "#{artist.artist_name} hasn't uploaded a profile image yet" %></p>
            <% end %>
            </div>
          <% else %>
          <%= link_to artist_path(artist) do %>
            <img class="image-show" src="<%= artist.artist_profile.profile_image %>" width="210" height="210" />
          <% end %>
          <% end %>
        </div>
        <div class="artist-discover-artist-artist-name">
          <%= link_to artist.artist_name, artist_path(artist) %>
        </div>
        <div class="fan-artist-following-page-genre">
           <%= artist.artist_profile.genre.downcase %>
        </div>
        <div class="artist-follower-page-fan-following">
            has <span class="artist-follower-page-fan-following-count"><%= link_to artist.fans.count, artist_followers_path(artist) %></span>
            <% if artist.fans.count == 1 %>
            fan
            <% else %>
            fans
            <% end %>
          </div>
      </div>
    <% end %>
  </div>


</div>
<%= render 'partials/home_footer' %>

app/views/static_pages/privacy.html.erb
<%= provide(:title, "Privacy") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">

  </div>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/sign_in.html.erb
<%= provide(:title, "Sign In As") %>
<%= render 'partials/static_pages_header' %>
<div class="container">
  <p class="i-am">I am a(n)...</p>
  <%= link_to "fan", fan_session_path, class: "signup-text-left" %>
  <%= link_to "artist", artist_session_path, class: "signup-text-right" %>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/sign_up.html.erb
<%= provide(:title, "Sign Up As") %>
<%= render 'partials/static_pages_header' %>
<div class="container">
  <p class="i-am">I am a(n)...</p>
  <%= link_to "fan", new_fan_registration_path, class: "signup-text-left" %>
  <%= link_to "artist", new_artist_registration_path, class: "signup-text-right" %>
</div>
<%= render 'partials/static_pages_footer' %>

app/views/static_pages/terms_of_use.html.erb
<%= provide(:title, "Terms of Use") %>
<%= render 'partials/static_pages_header' %>
<div class="landing-container">
  <div class="landing-content">
    <p><strong>Acceptance of the Use of Beats Realm Terms of Service</strong></p>

    <p>Your access to and use of Beats Realm is subject exclusively to these Terms of Service. You will not use the Website for any purpose that is unlawful or prohibited by these Terms of Service. By using the Website you are fully accepting the terms, conditions and disclaimers contained in this notice. If you do not accept these Terms of Service you must immediately stop using the Website.</p>

    <p><h3>Credit card details</h3></p>

    <p>Beats Realm will never ask for Credit Card details and request that you do not enter it on any of the forms on Beats Realm.</p>

    <p><h3>Advice</h3></p>

    <p>The contents of Beats Realm website do not constitute advice and should not be relied upon in making or refraining from making, any decision.</p>

    <p><h3>Change of Use</h3></p>

    <p><strong>Beats Realm reserves the right to:</strong></p>

    <p>change or remove (temporarily or permanently) the Website or any part of it without notice and you confirm that Beats Realm shall not be liable to you for any such change or removal and.
     <p>change these Terms of Service at any time, and your continued use of the Website following any changes shall be deemed to be your acceptance of such change.

     <p><h3>Links to Third Party Websites</h3></p>

    <p>Beats Realm Website may include links to third party websites that are controlled and maintained by others. Any link to other websites is not an endorsement of such websites and you acknowledge and agree that we are not responsible for the content or availability of any such sites.</p>

    <p><strong>Copyright</strong></p>

    <p>All copyright, trade marks and all other intellectual property rights in the Website and its content (including without limitation the Website design, text, graphics and all software and source codes connected with the Website) are owned by or licensed to Beats Realm or otherwise used by Beats Realm as permitted by law.</p>
    <p>In accessing the Website you agree that you will access the content solely for your personal, non-commercial use. None of the content may be downloaded, copied, reproduced, transmitted, stored, sold or distributed without the prior written consent of the copyright holder. This excludes the downloading, copying and/or printing of pages of the Website for personal, non-commercial home use only.</p>

    <p><strong>Disclaimers and Limitation of Liability</strong></p>

    <p>The Website is provided on an AS IS and AS AVAILABLE basis without any representation or endorsement made and without warranty of any kind whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose, non-infringement, compatibility, security and accuracy.</p>
    <p>To the extent permitted by law, Beats Realm will not be liable for any indirect or consequential loss or damage whatever (including without limitation loss of business, opportunity, data, profits) arising out of or in connection with the use of the Website.</p>
    <p>Beats Realm makes no warranty that the functionality of the Website will be uninterrupted or error free, that defects will be corrected or that the Website or the server that makes it available are free of viruses or anything else which may be harmful or destructive.</p>
    <p>Nothing in these Terms of Service shall be construed so as to exclude or limit the liability of Beats Realm for death or personal injury as a result of the negligence of Beats Realm or that of its employees or agents.</p>

    <p><strong>Indemnity</strong></p>


    <p>You agree to indemnify and hold Beats Realm and its employees and agents harmless from and against all liabilities, legal fees, damages, losses, costs and other expenses in relation to any claims or actions brought against Beats Realm arising out of any breach by you of these Terms of Service or other liabilities arising out of your use of this Website.</p>

    <p><strong>Severance</strong></p>

    <p>If any of these Terms of Service should be determined to be invalid, illegal or unenforceable for any reason by any court of competent jurisdiction then such Term or Condition shall be severed and the remaining Terms of Service shall survive and remain in full force and effect and continue to be binding and enforceable.</p>

    <p><strong>Governing Law</strong></p>

    <p>These Terms of Service shall be governed by and construed in accordance with the law of the United States of America and you hereby submit to the exclusive jurisdiction of the United States of America courts.</p>

    <p><strong>Contacting Us</strong></p>

    <p>If there are any questions regarding these Terms of Service you may contact us using the information below.</p>

    <p>Beats Realm Contact</p>
    <p>Alex Heil</p>
    <p>12068 MILLION DOLLAR HWY</p>
    <p>MEDINA, NEW YORK 14103</p>
    <p>alexheil@beatsrealm.com</p>
  </div>
</div>
<%= render 'partials/static_pages_footer' %>