config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'copyright' => 'static_pages#copyright'
  get 'sign_up' => 'static_pages#sign_up'
  get 'sign_in' => 'static_pages#sign_in'

  devise_for :artists, controllers: { sessions: "artists/sessions", passwords: "artists/passwords", registrations: "artists/registrations", confirmations: "artists/confirmations",  unlocks: "artists/unlocks"}

  resources :artists, controller: 'artists/artists', only: [:show, :index] do
    member do
      resource :profile, controller: 'artists/profiles', only: [:edit, :update], as: :artist_profile
    end
    member do
      resources :albums, controller: 'artists/albums', only: [:index, :new, :create], as: :artist_albums
    end
    collection do
      resources :albums, controller: 'artists/albums', only: [:show, :edit, :update, :destroy], as: :artist_albums do
        member do
          resources :tracks, controller: 'artists/tracks', only: [:new, :create], as: :artist_tracks
        end
        collection do
          resources :tracks, controller: 'artists/tracks', only: [:show, :edit, :update, :destroy], as: :artist_tracks
        end
      end
    end
    member do
      resources :videos, controller: 'artists/videos', only: [:index, :new, :create], as: :artist_videos
    end
    collection do
      resources :videos, controller: 'artists/videos', only: [:edit, :update, :destroy], as: :artist_videos
    end
    member do
      resources :shows, controller: 'artists/shows', only: [:index, :new, :create], as: :artist_shows
    end
    collection do
      resources :shows, controller: 'artists/shows', only: [:edit, :update, :destroy], as: :artist_shows
    end
    member do
      resources :merch, controller: 'artists/merches', only: [:index, :new, :create], as: :artist_merches
    end
    collection do
      resources :merch, controller: 'artists/merches', only: [:show, :edit, :update, :destroy], as: :artist_merches do
        member do
          resources :purchases, controller: 'artists/merch_purchases', only: :create, as: :artist_merch_purchases
        end
        collection do
          resources :purchases, controller: 'artists/merch_purchases', only: [:edit, :update, :destroy], as: :artist_merch_purchases
        end
      end
    end
    member do
      resources :microposts, controller: 'artists/microposts', only: :create, as: :artist_microposts
    end
    collection do
      resources :microposts, controller: 'artists/microposts', only: :destroy, as: :artist_microposts do
        member do
          resources :comments, controller: 'artists/comments', only: :create, as: :artist_micropost_comments
        end
        collection do
          resources :comments, controller: 'artists/comments', only: :destroy, as: :artist_micropost_comments
        end
      end
    end
    member do
      resources :relationships, only: :create
    end
    collection do
      resources :relationships, only: :destroy
    end
  end

  get 'artists/:id/select_albums' => 'artists/albums#select', as: :select_artist_album
  get 'artists/:id/select_videos' => 'artists/videos#select', as: :select_artist_video
  get 'artists/:id/select_shows' => 'artists/shows#select', as: :select_artist_show
  get 'artists/:id/select_merch' => 'artists/merches#select', as: :select_artist_merch
  get 'artists/:id/merch_transactions' => 'artists/merch_purchases#index', as: :artist_merch_transactions
  get 'artists/merch/purchases/:id/edit_shipped' => 'artists/merch_purchases#edit_shipped', as: :artist_merch_transactions_edit_shipped
  get 'artists/:id/followers' => 'artists/artists#followers', as: :artist_followers

  devise_scope :artist do
    get "sign_out", to: "artists/sessions#destroy"
  end

  devise_for :fans, controllers: { sessions: "fans/sessions", passwords: "fans/passwords", registrations: "fans/registrations", confirmations: "fans/confirmations",  unlocks: "fans/unlocks"}

  resources :fans, controller: 'fans/fans', only: :show do
    member do
      resource :profile, controller: 'fans/profiles', only: [:edit, :update], as: :fan_profile
    end
  end

  get 'fans/:id/purchase_history' => 'fans/merch_purchases#index', as: :fan_purchase_history
  get 'fans/:id/following' => 'fans/fans#following', as: :fan_following

  devise_scope :fan do
    get "sign_out", to: "fans/sessions#destroy"
  end

end

app/controllers/artists/albums_controller.rb
class Artists::AlbumsController < ApplicationController

  before_action :authenticate_artist!, except: [:index, :show]
  before_action :correct_artist, except: [:index, :show, :edit, :update, :destroy]
  before_action :set_artist, except: [:index, :show]
  before_action :correct_album_artist, only: [:edit, :update, :destroy]

  def index
    @artist = Artist.find(params[:id])
  end

  def select
    @album = ArtistAlbum.all
  end

  def show
    @album = ArtistAlbum.find(params[:id])
    @artist = Artist.find(@album.artist_id)
  end

  def new
    @album = ArtistAlbum.new
  end

  def create
    @album = @artist.artist_albums.build(album_params)
    if @album.save
      redirect_to select_artist_album_path(@artist)
    else
      render 'new'
    end
  end

  def edit
    @album = ArtistAlbum.find(params[:id])
  end

  def update
    @album = ArtistAlbum.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to select_artist_album_path(@artist)
    else
      render 'new'
    end
  end

  def destroy
    ArtistAlbum.find(params[:id]).destroy
    redirect_to select_artist_album_path(@artist)
  end

  private

    def set_artist
      @artist = current_artist
    end

    def correct_artist
      @artist = current_artist
      redirect_to artist_path if @artist != Artist.find(params[:id])
    end

    def correct_album_artist
      @album = ArtistAlbum.find(params[:id])
      redirect_to artist_path(@album.artist_id) if @album.artist_id != current_artist.id
    end

    def album_params
      params.require(:artist_album).permit(:album_name, :album_year, :album_cover_art_url)
    end

end

app/controllers/artists/artists_controller.rb
class Artists::ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.includes(:artist_microposts).find(params[:id])
    @micropost = ArtistMicropost.new
  end

  def followers
    @artist = Artist.find(params[:id])
  end

end


app/controllers/artists/comments_controller.rb
class Artists::CommentsController < ApplicationController

  before_action :authenticate_commenter, only: :create

  def create
    @comment = ArtistMicropostComment.new(comment_params)
    if artist_signed_in?
      @comment.artist_id = current_artist.id
      @comment.artist_name = current_artist.artist_name
    elsif fan_signed_in?
      @comment.fan_id = current_fan.id
      @comment.fan_name = current_fan.fan_name
    end
    if @comment.save
      redirect_to (:back)
    else
      redirect_to root_url
    end
  end

  def destroy
    ArtistMicropostComment.find(params[:id]).destroy
    redirect_to (:back)
  end

  private

    def authenticate_commenter
      authenticate_artist! unless fan_signed_in? || authenticate_fan! unless artist_signed_in?
    end

    def comment_params
      params.require(:artist_micropost_comment).permit(:artist_micropost_id, :content, :upvotes, :downvotes, :total_votes)
    end
end

app/controllers/artists/confirmations_controller.rb
class Artists::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/artists/merch_purchases_controller.rb
class Artists::MerchPurchasesController < ApplicationController

  before_action :authenticate_artist!, only: [:index, :edit_shipped]
  before_action :authenticate_fan!, except: [:index, :edit_shipped, :update]
  before_action :authenticate_artist_fan, only: :update
  before_action :set_artist, only: :index
  before_action :correct_artist, only: :index
  before_action :correct_purchase_fan, only: :edit


  def index
    @purchases = ArtistMerchPurchase.all
  end

  def create
    @purchase = ArtistMerchPurchase.new(purchase_params)
    @merch = ArtistMerch.find(params[:id])
    @artist = Artist.find(@merch.artist_id)
    @fan = current_fan

    @purchase.artist_id = @artist.id
    @purchase.merch_name = @merch.merch_name
    @purchase.base_price = @merch.base_price
    @purchase.shipping_price = @merch.shipping_price
    @purchase.fan_id = @fan.id
    @purchase.fan_username = @fan.username

    if @purchase.save
      redirect_to edit_artist_merch_purchase_path(@purchase)
    else
      redirect_to (:back)
    end
  end

  def edit
    @purchase = ArtistMerchPurchase.find(params[:id])
    @merch = ArtistMerch.find(@purchase.artist_merch_id)
    @artist = Artist.find(@merch.artist_id)
  end

  def edit_shipped
    @purchase = ArtistMerchPurchase.find(params[:id])
    @merch = ArtistMerch.find(@purchase.artist_merch_id)
    @artist = Artist.find(@merch.artist_id)
  end

  def update
    @purchase = ArtistMerchPurchase.find(params[:id])
    @merch = ArtistMerch.find(@purchase.artist_merch_id)
    @artist = Artist.find(@merch.artist_id)
    if fan_signed_in? && @purchase.update_attributes(purchase_params)
      redirect_to artist_path(@artist)
    elsif artist_signed_in? && @purchase.update_attributes(purchase_params)
      redirect_to artist_merch_transactions_path(current_artist)
    else
      render 'edit'
    end
  end

  def destroy
    ArtistMerchPurchase.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def purchase_params
      params.require(:artist_merch_purchase).permit(:artist_id, :artist_merch_id, :quantity, :pay_your_own_price, :complete_price, :full_name, :street_address, :city, :state, :country, :zip_code, :is_shipped)
    end

    def set_artist
      @artist = current_artist
    end

    def correct_artist
      @artist = current_artist
      redirect_to artist_path if @artist != Artist.find(params[:id])
    end

    def correct_purchase_fan
        @purchase = ArtistMerchPurchase.find(params[:id])
        redirect_to artist_path(@purchase.artist_id) if @purchase.fan_id != current_fan.id
    end

    def authenticate_artist_fan
      authenticate_artist! unless fan_signed_in? || authenticate_fan! unless artist_signed_in?
    end

end

app/controllers/artists/merches_controller.rb
class Artists::MerchesController < ApplicationController

  before_action :authenticate_artist!, except: [:index, :show]
  before_action :correct_artist, except: [:index, :show, :edit, :update, :destroy]
  before_action :set_artist, except: [:index, :show]
  before_action :correct_merch_artist, only: [:edit, :update, :destroy]

  def index
    @artist = Artist.find(params[:id])
    @merch = ArtistMerch.all
  end

  def select
    @merch = ArtistMerch.all
  end

  def show
    @merch = ArtistMerch.find(params[:id])
    @artist = Artist.find(@merch.artist_id)
  end

  def new
    @merch = ArtistMerch.new
  end

  def create
    @merch = @artist.artist_merches.build(merch_params)
    if @merch.save
      redirect_to select_artist_merch_path(@artist)
    else
      render 'new'
    end
  end

  def edit
    @merch = ArtistMerch.find(params[:id])
  end

  def update
    @merch = ArtistMerch.find(params[:id])
    if @merch.update_attributes(merch_params)
      redirect_to select_artist_merch_path(@artist)
    else
      render 'new'
    end
  end

  def destroy
    ArtistMerch.find(params[:id]).destroy
    redirect_to select_artist_merch_path(@artist)
  end

  private

    def merch_params
      params.require(:artist_merch).permit(:paypal_email, :about, :merch_name, :merch_description, :base_price, :shipping_price, :total_price, :quantity, :options, :return_policy, :shipping_info, :merch_image)
    end

    def set_artist
      @artist = current_artist
    end

    def correct_artist
      @artist = current_artist
      redirect_to artist_path if @artist != Artist.find(params[:id])
    end

    def correct_merch_artist
      @merch = ArtistMerch.find(params[:id])
      redirect_to artist_path(@merch.artist_id) if @merch.artist_id != current_artist.id
    end

end

app/controllers/artists/microposts_controller.rb
class Artists::MicropostsController < ApplicationController

  before_action :authenticate_artist!
  before_action :set_artist
  before_action :correct_artist, only: :create
  before_action :correct_micropost_artist, only: :destroy

  def create
    @micropost = @artist.artist_microposts.build(micropost_params)
    if @micropost.save
      redirect_to @artist
    else
      redirect_to root_url
    end
  end

  def destroy
    ArtistMicropost.find(params[:id]).destroy
    redirect_to (:back)
  end

  private

    def set_artist
      @artist = current_artist
    end

    def correct_artist
      @artist = current_artist
      redirect_to artist_path if @artist != Artist.find(params[:id])
    end

    def correct_micropost_artist
      @micropost = ArtistMicropost.find(params[:id])
      redirect_to artist_path(@micropost.artist_id) if @micropost.artist_id != current_artist.id
    end

    def micropost_params
      params.require(:artist_micropost).permit(:artist_id, :content, :upvotes, :downvotes, :total_votes)
    end

end

app/controllers/artists/omniauth_callbacks_controller.rb
class Artists::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/artists/passwords_controller.rb
class Artists::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/artists/profiles_controller.rb
class Artists::ProfilesController < ApplicationController

  before_action :authenticate_artist!
  before_action :correct_artist
  before_action :set_artist

  def edit
    @profile = @artist.artist_profile
  end

  def update
    @profile = @artist.artist_profile
    if @profile.update_attributes(profile_params)
      redirect_to current_artist
    else
      render 'edit'
    end
  end

  private

    def set_artist
      @artist = current_artist
    end

    def correct_artist
      @artist = current_artist
      redirect_to artist_path if @artist != Artist.find(params[:id])
    end

    def profile_params
      params.require(:artist_profile).permit(:biography, :location, :genre, :members, :facebook_url, :twitter_url, :youtube_url, :itunes_url, :amazon_url, :google_play_url, :record_label, :cover_image, :profile_image)
    end

end

app/controllers/artists/sessions_controller.rb
class Artists::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/artists/unlocks_controller.rb
class Artists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/artists/albums/edit.html.erb
<div class="container">
  <div class="landing-container">
    <div class="artist-add-new-track-button-container">
      <%= link_to "add new track to this album", new_artist_track_path, class: "artist-add-new-track-button" %>
    </div>
    <% if @album.artist_tracks.any? %>
    <div class="artist-album-track-listing">
      <p class="artist-album-track-listing-title">track listing</p>
      <% @album.artist_tracks.each do |track| %>
      <div class="artist-album-track-listing-tracks">
        <%= track.track_number %> - <%= link_to track.track_name, edit_artist_track_path(track) %>
        <% if @artist == current_artist %>
             // <%= link_to "delete track", artist_track_path(track), data: { confirm: "Are you sure? This cannot be undone. Ever..." }, method: :delete %></span>
            <% end %>
      </div>
      <% end %>
    </div>
    <% end %>
    <div class="form-title">
      <h3>edit album</h3>
    </div>
    <%= form_for(@album, url: artist_album_path) do |f| %>
      <div class="field">
        <%= f.label :album_name, "album name", class: "label" %>
        <%= f.text_field :album_name, class: "text-field" %>
      </div>
      <div class="field">
        <%= f.label :album_year, "album year", class: "label" %>
        <%= f.text_field :album_year, class: "text-field" %>
      </div>
      <div class="field">
        <%= f.label :album_cover_art_url, "album cover art url", class: "label" %>
        <%= f.text_field :album_cover_art_url, class: "text-field" %>
      </div>
      <div class="actions">
        <%= f.submit "add album", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/albums/index.html.erb
<%= provide(:title, "#{@artist.artist_name} | Albums") %>
<div class="container">
  <%= render "/artists/partials/artists_cover_photo_show_nav" %>
  <div class="artist-show-left">
    <div class="artist-show-title">
      <%= @artist.artist_name %>
    </div>
    <div class="artist-show-profile">
    <% if @artist.artist_albums.any? %>
    <% @artist.artist_albums.each do |album| %>
      <div class="artist-album-container">
        <div class="artist-album-image">
          <%= link_to artist_album_path(album) do %>
            <img class="image-show" src="<%= album.album_cover_art_url %>" width="280" height="280" />
          <% end %>
        </div>
        <div class="artist-album-name">
          <%= link_to album.album_name, artist_album_path(album)  %>
        </div>
        <div class="artist-album-year">
          <%= album.album_year %>
        </div>
          <% if @artist == current_artist %>
            <div>
              <%= link_to 'edit', edit_artist_album_path(album) %>
            </div>
          <% end %>
      </div>
    <% end %>
    <% else %>
      <p class="no-artist-show-profile"><%= "#{@artist.artist_name} hasn't uploaded any albums yet" %></p>
    <% end %>
    </div>
  </div>
  <%= render "artists/partials/artist_sidebar" %>
</div>
<%= render "partials/static_pages_footer" %>

app/views/artists/albums/new.html.erb
<div class="container">
  <div class="landing-container">
    <div class="form-title">
      <h3>add an album</h3>
    </div>
    <%= form_for(@album, url: artist_albums_path(@artist)) do |f| %>
      <div class="field">
        <%= f.label :album_name, "album name", class: "label" %>
        <%= f.text_field :album_name, class: "text-field" %>
      </div>
      <div class="field">
        <%= f.label :album_year, "album year", class: "label" %>
        <%= f.text_field :album_year, class: "text-field" %>
      </div>
      <div class="field">
        <%= f.label :album_cover_art_url, "album cover art url", class: "label" %>
        <%= f.text_field :album_cover_art_url, class: "text-field" %>
      </div>
      <div class="actions">
        <%= f.submit "add album", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/albums/select.html.erb
<div class="container">
  <div class="landing-container">
    <div class="artist-add-new-album-button-container">
      <%= link_to "add an album", new_artist_album_path, class: "artist-add-new-album-button" %>
    </div>
    <% if @artist.artist_albums.any? %>
    <p class="artist-album-title-option">or click on an album below to edit it</p>
      <% @artist.artist_albums.each do |album| %>
        <div class="artist-album-title-select">
          <%= link_to album.album_name, edit_artist_album_path(album) %> // <%= link_to "delete album", artist_album_path(album), data: { confirm: "Are you sure? This cannot be undone. Ever..." }, method: :delete %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/artists/albums/show.html.erb
<%= provide(:title, "#{@artist.artist_name} | #{@album.album_name}") %>
<div class="container">
  <%= render "/artists/partials/artists_cover_photo_show_nav" %>
  <div class="artist-show-left">
    <div class="artist-show-title">
      <%= @artist.artist_name %>
    </div>
    <div class="artist-show-profile">


      <div class="artist-album-indv-container">
        <div class="artist-album-indiv-image">
          <% if @album.album_cover_art_url == "" %>
            no image yet
          <% else %>
            <img class="image-show artist-album-cover-art-click" src="<%= @album.album_cover_art_url %>" width="450" height="450" />

            <div class="artist-album-lightbox-shadow">
            </div>
            <div class="artist-album-lightbox">
              <img src="<%= @album.album_cover_art_url %>" width="900" height="900" />
            </div>

          <% end %>
        </div>


        <div class="artist-album-indiv-information">
          <div class="artist-album-indiv-title">
            <%= @album.album_name %><span class="artist-album-indiv-year"> // <%= @album.album_year %></span>
          </div>
          </br>
          <div class="artist-album-indiv-track-title">
            <% if @album.artist_tracks.any? %>
              <% @album.artist_tracks.take(1).each do |track| %>
                <%= track.track_name %>
              <% end %>
            <% end %>
          </div>

            <div class="artist-track-playlist-container">
            <audio id="music" preload="true">
              <% if @album.artist_tracks.any? %>
                <% @album.artist_tracks.take(1).each do |track| %>
                <source src="<%= track.track_url %>">
                </source>
                <% end %>
              <% end %>
            </audio>
            <div id="audioplayer">
              <button id="pButton" class="play" ></button>
              <div id="current_time">00:00</div>
              <div id="timeline">
                    <div id="playhead"></div>
              </div>
              <div id="total_duration">00:00</div>
            </div>
          </div>

        </div>
      </div>

      <div class="artist-album-indiv-container">
        <div class="artist-album-track-indiv-info-title-left">
          <p class="artist-album-indiv-info-title">track listing //</p>
        </div>
        <div class="artist-album-track-indiv-info-title-right">
          <p class="artist-album-indiv-info-title">lyrics //</p>
        </div>
      </div>

      <div class="artist-album-indiv-container">
        <% if @album.artist_tracks.any? %>
          <% @album.artist_tracks.each do |track| %>
        <div class="artist-album-indiv-info-left">
            <div class="artist-album-track-listing-album-page">
              <span class="artist-album-track-listing-mini-play">></span><span class="artist-album-track-url"><%= track.track_url %></span> <%= track.track_number %> - <span class="artist-album-track-title"><%= link_to track.track_name, artist_track_path(track) %></span>
            </div>
        </div>
        <div class="artist-album-indiv-info-right">
            <div class="artist-album-track-lyrics">
              <% if track.track_lyrics != "" %>
                <%= track.track_lyrics %>
              <% end %>
            </div>
        </div>
          <% end %>
        <% end %>
      </div>

      <div class="artist-album-indiv-container">
        <% @artist.artist_albums.each do |album| %>
          <div class="artist-album-container">
            <div class="artist-album-image">
              <%= link_to artist_album_path(album) do %>
                <img class="image-show" src="<%= album.album_cover_art_url %>" width="280" height="280" />
              <% end %>
            </div>
            <div class="artist-album-name">
              <%= link_to album.album_name, artist_album_path(album)  %>
            </div>
            <div class="artist-album-year">
              <%= album.album_year %>
            </div>
              <% if @artist == current_artist %>
                <div>
                  <%= link_to 'edit', edit_artist_album_path(album) %>
                </div>
              <% end %>
          </div>
        <% end %>
      </div>


    </div>
  </div>
  <%= render "artists/partials/artist_sidebar" %>
</div>
<%= render "partials/static_pages_footer" %>