config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'copyright' => 'static_pages#copyright'
  get 'sign_up' => 'static_pages#sign_up'
  get 'sign_in' => 'static_pages#sign_in'

  devise_for :artists, controllers: { sessions: "artists/sessions", passwords: "artists/passwords", registrations: "artists/registrations", confirmations: "artists/confirmations",  unlocks: "artists/unlocks"}

  resources :artists, controller: 'artists/artists', only: [:show, :index] do
    member do
      resource :profile, controller: 'artists/profiles', only: [:edit, :update], as: :artist_profile
    end
    member do
      resources :albums, controller: 'artists/albums', only: [:index, :new, :create], as: :artist_albums
    end
    collection do
      resources :albums, controller: 'artists/albums', only: [:show, :edit, :update, :destroy], as: :artist_albums do
        member do
          resources :tracks, controller: 'artists/tracks', only: [:new, :create], as: :artist_tracks
        end
        collection do
          resources :tracks, controller: 'artists/tracks', only: [:show, :edit, :update, :destroy], as: :artist_tracks
        end
      end
    end
    member do
      resources :videos, controller: 'artists/videos', only: [:index, :new, :create], as: :artist_videos
    end
    collection do
      resources :videos, controller: 'artists/videos', only: [:edit, :update, :destroy], as: :artist_videos
    end
    member do
      resources :shows, controller: 'artists/shows', only: [:index, :new, :create], as: :artist_shows
    end
    collection do
      resources :shows, controller: 'artists/shows', only: [:edit, :update, :destroy], as: :artist_shows
    end
    member do
      resources :merch, controller: 'artists/merches', only: [:index, :new, :create], as: :artist_merches
    end
    collection do
      resources :merch, controller: 'artists/merches', only: [:show, :edit, :update, :destroy], as: :artist_merches do
        member do
          resources :purchases, controller: 'artists/merch_purchases', only: :create, as: :artist_merch_purchases
        end
        collection do
          resources :purchases, controller: 'artists/merch_purchases', only: [:edit, :update, :destroy], as: :artist_merch_purchases
        end
      end
    end
    member do
      resources :microposts, controller: 'artists/microposts', only: :create, as: :artist_microposts
    end
    collection do
      resources :microposts, controller: 'artists/microposts', only: :destroy, as: :artist_microposts do
        member do
          resources :comments, controller: 'artists/comments', only: :create, as: :artist_micropost_comments
        end
        collection do
          resources :comments, controller: 'artists/comments', only: :destroy, as: :artist_micropost_comments
        end
      end
    end
    member do
      resources :relationships, only: :create
    end
    collection do
      resources :relationships, only: :destroy
    end
  end

  get 'artists/:id/select_albums' => 'artists/albums#select', as: :select_artist_album
  get 'artists/:id/select_videos' => 'artists/videos#select', as: :select_artist_video
  get 'artists/:id/select_shows' => 'artists/shows#select', as: :select_artist_show
  get 'artists/:id/select_merch' => 'artists/merches#select', as: :select_artist_merch
  get 'artists/:id/merch_transactions' => 'artists/merch_purchases#index', as: :artist_merch_transactions
  get 'artists/merch/purchases/:id/edit_shipped' => 'artists/merch_purchases#edit_shipped', as: :artist_merch_transactions_edit_shipped
  get 'artists/:id/followers' => 'artists/artists#followers', as: :artist_followers

  devise_scope :artist do
    get "sign_out", to: "artists/sessions#destroy"
  end

  devise_for :fans, controllers: { sessions: "fans/sessions", passwords: "fans/passwords", registrations: "fans/registrations", confirmations: "fans/confirmations",  unlocks: "fans/unlocks"}

  resources :fans, controller: 'fans/fans', only: :show do
    member do
      resource :profile, controller: 'fans/profiles', only: [:edit, :update], as: :fan_profile
    end
  end

  get 'fans/:id/purchase_history' => 'fans/merch_purchases#index', as: :fan_purchase_history
  get 'fans/:id/following' => 'fans/fans#following', as: :fan_following

  devise_scope :fan do
    get "sign_out", to: "fans/sessions#destroy"
  end

end

app/models/fan.rb
class Fan < ActiveRecord::Base
devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable
 #:omniauthable

  has_one :fan_profile, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :artists, through: :relationships
  belongs_to :artist

  has_many :artist_microposts, through: :artists
  has_many :artist_shows, through: :artists

  has_many :artist_micropost_comments, dependent: :destroy
  has_many :artist_merch_purchases, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :fan_name, presence: true, length: { maximum: 50 }

  before_save :downcase_username

  def following?(artist)
    Relationship.exists? fan_id: id, artist_id: artist.id
  end

  def unfollow(artist)
    Relationship.find_by(fan_id: id, artist_id: artist.id).destroy
  end

  private

    def downcase_username
      self.username = username.downcase
    end

end

app/controllers/fans/confirmations_controller.rb
class Fans::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/fans/fans_controller.rb
class Fans::FansController < ApplicationController

  def index
  end

  def show
    @fan = Fan.find(params[:id])
  end

  def following
    @fan = Fan.find(params[:id])
  end

end

app/controllers/fans/merch_purchases_controller.rb
class Fans::MerchPurchasesController < ApplicationController

  before_action :authenticate_fan!
  before_action :correct_fan


  def index
    @fan = current_fan
    @purchases = ArtistMerchPurchase.all
  end

  private

    def correct_fan
      @fan = current_fan
      redirect_to fan_path if @fan != Fan.find(params[:id])
    end

end

app/controllers/fans/omniauth_callbacks_controller.rb
class Fans::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/fans/passwords_controller.rb
class Fans::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/fans/profiles_controller.rb
class Fans::ProfilesController < ApplicationController

  before_action :authenticate_fan!
  before_action :correct_fan
  before_action :set_fan

  def edit
    @profile = @fan.fan_profile
  end

  def update
    @profile = @fan.fan_profile
    if @profile.update_attributes(profile_params)
      redirect_to current_fan
    else
      render 'edit'
    end
  end

  private

    def set_fan
      @fan = current_fan
    end

    def correct_fan
      @fan = current_fan
      redirect_to fan_path if @fan != Fan.find(params[:id])
    end

    def profile_params
      params.require(:fan_profile).permit(:biography, :location, :website, :cover_image, :profile_image)
    end

end

app/controllers/fans/registrations_controller.rb
class Fans::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    @fan.create_fan_profile(profile_params)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

     def profile_params
      params.permit(:biography, :location, :website, :cover_image, :profile_image)
    end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/fans/sessions_controller.rb
class Fans::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/fans/unlocks_controller.rb
class Fans::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/fans/fans/following.html.erb
<div class="container">
  <%= render "fans/partials/fan_cover_image" %>
  <div class="fan-is-following-title">
    <%= @fan.fan_name %> is following //
  </div>

  <% if @fan.artists.any? %>
    <% @fan.artists.each do |artist| %>
        <div class="fan-artist-following-page-container">
          <div class="fan-artist-following-page-profile-image">
            <% if artist.artist_profile.profile_image == "" %>
            <div class="fan-artist-following-page-no-artist-profile-image">
              <% if artist_signed_in? && artist.id == current_artist.id %>
              <p class="fan-no-profile-image-yet">you do not have a profile photo yet</p>
              <p><%= link_to "upload a profile image", edit_artist_profile_path(current_artist), class: "upload-fan-profile-image" %></p>
              <% else %>
              <p class="fan-no-profile-image-yet"><%= "#{artist.artist_name} hasn't uploaded a profile image yet" %></p>
              <% end %>
              </div>
            <% else %>
            <%= link_to artist_path(artist) do %>
              <img class="image-show" src="<%= artist.artist_profile.profile_image %>" width="210" height="210" />
            <% end %>
            <% end %>
          </div>
          <div class="fan-artist-following-page-artist-name">
            <%= link_to "#{artist.artist_name}", artist_path(artist) %>
          </div>
          <div class="fan-artist-following-page-genre">
           <%= artist.artist_profile.genre %>
          </div>
          <div class="fan-artist-following-page-artist-followers">
            has <span class="fan-artist-following-page-artist-followers-count"><%= link_to artist.fans.count - 1, artist_followers_path(artist) %></span> other
            <% if artist.fans.count - 1 == 1 %>
            fan
            <% else %>
            fans
            <% end %>
          </div>
        </div>
    <% end %>
  <% end %>

</div>
<%= render "partials/static_pages_footer" %>

app/views/fans/fans/show.html.erb
<div class="container">
  <%= render "fans/partials/fan_cover_image" %>

  <div class="fan-side-profile">
    <div class="fan-show-title">
      <%= @fan.fan_name %>
    </div>
    <div class="artist-sidebar-fans-follow">
      following <span class="artist-sidebar-fans-number">
      <% if @fan.artists.count > 0 %>
        <%= link_to @fan.artists.count, fan_following_path %>
      <% else %>
        <%= @fan.artists.count %>
      <% end %>
      </span>
      <% if @fan.artists.count == 1 %>
        artist
      <% else %>
        artists
      <% end %>
    </div>
    <% if fan_signed_in? && @fan.id == current_fan.id && @fan.fan_profile.location == "" && @fan.fan_profile.biography == "" && @fan.fan_profile.website == "" %>
    <p class="no-fan-show-profile">you do not have any profile information</p>
    <div class="no-fan-show-profile-button-container">
      <%= link_to "update your profile", edit_fan_profile_path, class: "no-fan-show-profile-button" %>
    </div>
    <% elsif @fan.fan_profile.location == "" && @fan.fan_profile.biography == "" && @fan.fan_profile.website == "" %>
    <p class="no-fan-show-profile"><%= "#{@fan.fan_name} does not have any profile information yet" %></p>
    <% end %>
    <% if @fan.fan_profile.location == "" %>
    <% else %>
    <p class="fan-show-profile-title">location //</p>
    <p class="fan-show-profile-description"><%= @fan.fan_profile.location %></p>
    <% end %>
    <% if @fan.fan_profile.website == "" %>
    <% else %>
    <p class="fan-show-profile-title">website //</p>
    <p class="fan-show-profile-description"><%= link_to "#{@fan.fan_profile.website}", @fan.fan_profile.website %></p>
    <% end %>
    <% if @fan.fan_profile.biography == "" %>
    <% else %>
    <p class="fan-show-profile-title">biography //</p>
    <p class="fan-show-profile-description"><%= @fan.fan_profile.biography %></p>
    <% end %>
  </div>

  <div class="fan-content">

    <div class="fan-artist-micropost-feed-title">
      <%= @fan.fan_name %>'s status feed
    </div>
    <% if @fan.artist_microposts.any? %>
      <% @fan.artist_microposts.take(20).each do |micropost| %>
        <div class="fan-artist-micropost-feed">
          <div class="fan-artist-micropost-posted-by">
          <span class="fan-artist-posted-by"><%= link_to Artist.find(micropost.artist_id).artist_name, artist_path(micropost.artist_id) %></span><span class="fan-artist-posted-time-ago"> posted <%= time_ago_in_words(micropost.created_at) %> ago
            <% if artist_signed_in? && micropost.artist_id == current_artist.id %>
             // <%= link_to "delete post", artist_micropost_path(micropost), data: { confirm: "Are you sure? This cannot be undone. Ever..." }, method: :delete %></span>
            <% end %></span>
          </div>
          <div class="fan-artist-micropost-content">
            <%= micropost.content %>
          </div>
          <div class="fan-artist-micropost-total-votes">
            <%= link_to "∧", '#' %> <%= micropost.total_votes %> <%= link_to "∨" , '#' %>
          </div>
          <div class="fan-artist-micropost-social">
            <%= micropost.artist_micropost_comments.count %> <a class="fan-artist-micropost-comment-click">comments</a>
          </div>
          <div class="fan-artist-micropost-comments-container">
          <% micropost.artist_micropost_comments.each do |comment| %>
            <div class="fan-artist-micropost-comments-name">
              <span class="comment-artist-fan-posted-by"><%= link_to Artist.find(comment.artist_id).artist_name, artist_path(comment.artist_id) if comment.fan_id.nil?%><%= link_to Fan.find(comment.fan_id).fan_name, fan_path(comment.fan_id) if comment.artist_id.nil?  %></span> posted <%= time_ago_in_words(comment.created_at) %> ago
              <% if (artist_signed_in? && micropost.artist_id == current_artist.id) || (artist_signed_in? && current_artist.id == comment.artist_id) || (fan_signed_in? && current_fan.id == comment.fan_id) %>
             // <%= link_to "delete comment", artist_micropost_comment_path(comment), data: { confirm: "Are you sure? This cannot be undone. Ever..." }, method: :delete %>
            <% end %>
            </div>
            <div class="fan-artist-micropost-comments-content">
              <%= comment.content %>
            </div>
            <div class="fan-artist-micropost-comment-total-votes">
              <%= link_to "∧", '#' %> <%= comment.total_votes %> <%= link_to "∨" , '#' %>
            </div>
          <% end %>
            <%= form_for(micropost.artist_micropost_comments.build) do |f| %>
            <div class="fan-artist-micropost-comment-form-container">
              <div class="fan-artist-micropost-comment-field">
                <%= f.hidden_field :artist_micropost_id %>
                <%= f.text_area :content, placeholder: "leave a comment // tell someone they suck", class: "fan-artist-micropost-comment-input" %>
              </div>
              <div class="artist-micropost-comment-actions">
                <%= f.submit "comment",  class: "fan-artist-micropost-comment-post-button" %>
              </div>
            </div>
          </div>
            <% end %>
        </div>
      <% end %>
    <% else %>
      no microposts
    <% end %>

    <% if @fan.fan_profile.location == "" %>
    <% else %>
    <div class="fan-artist-show-feed-title">
      shows coming to <%= @fan.fan_profile.location.split(",").first %> based on who <%= @fan.fan_name %> follows
    </div>
    <% if @fan.artist_shows.any? %>
      <% @fan.artist_shows.select{ |show| show.show_location == @fan.fan_profile.location }.each do |show| %>
        <div class="fan-artist-show-feed">
          <div class="fan-artist-show-feed-artist-name">
            <%= link_to Artist.find(show.artist_id).artist_name, artist_path(show.artist_id) %>
          </div>
          <div class="fan-artist-show-feed-date">
            <%= show.show_month %>.<%= show.show_day %>.<%= show.show_year %>
          </div>
          <div class="fan-artist-show-feed-venue">
            <%= show.show_venue %>
          </div>
          <div class="fan-artist-show-feed-tickets">
            <%= link_to "tickets", show.show_ticket_url if show.show_ticket_url != "" %>
          </div>
        </div>
      <% end %>
      <% else %>
      no shows coming to <%= @fan.fan_profile.location.split(",").first %>
      <% end %>
      <% end %>

</div>
<%= render "partials/static_pages_footer" %>